# Generated by Django 6.1 on 2026-09-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='first_name',
            new_name='full_name',
        ),
    ]
