# Generated by Django 6.0.6 on 2026-09-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('technologies', models.JSONField(default=list)),
                ('url', models.URLField(blank=True)),
                ('date', models.DateField()),
                ('slug', models.SlugField(editable=False, max_length=220, unique=True)),
            ],
        ),
    ]
