# Generated by Django 6.0.6 on 2026-09-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='technologies',
            new_name='languages',
        ),
    ]
